src/main/java/net/ap57/tiger/ext/iot/linecounter/entity/CounterDataId.java
/*
 * Copyright 2016 Arief Prihasanto <aphasan57 at gmail.com>.
 * All rights reserved

 * A lot of time, effort and money is spent designing and implementing the software.
 * All system design, text, graphics, the selection and arrangement thereof, and
 * all software compilations, underlying source code, software and all other material
 * on this software are copyright Arief Prihasanto <aphasan57 at gmail.com> and any affiliates.
 * 
 * In simple terms, every element of this software is protected by copyright.
 * Unless you have our express written permission, you are not allowed
 * to copy partially and or completely, modify partially and or completely,
 * use partially and or completely and or reproduce any part of this  software
 * in any way, shape and or form.
 * 
 * Taking material from other source code and or document Arief Prihasanto <aphasan57 at gmail.com> and affiliates has designed is
 * also prohibited. You can be prosecuted by the licensee as well as by us as licensor.
 * 
 * Any other use of materials of this software, including reproduction for purposes other
 * than that noted in the business agreement, modification, distribution, or republication,
 * without the prior written permission of Arief Prihasanto <aphasan57 at gmail.com> is strictly prohibited.
 * 
 * The source code, partially and or completely, shall not be presented and or shown
 * and or performed to public and or other parties without the prior written permission
 * of Arief Prihasanto <aphasan57 at gmail.com>

 */
package net.ap57.tiger.ext.iot.linecounter.entity;

import java.io.Serializable;
import java.util.Date;
import java.util.Objects;

/**
 *
 * @author Arief Prihasanto <aphasan57 at gmail.com>
 */
public class CounterDataId implements Serializable {

    private static final long serialVersionUID = 1L;
    
    private CounterPositionId counterPosition;
    
    private Date inputTime;

    public CounterPositionId getCounterPosition() {
        return counterPosition;
    }

    public void setCounterPosition(CounterPositionId counterPosition) {
        this.counterPosition = counterPosition;
    }

    public Date getInputTime() {
        return inputTime;
    }

    public void setInputTime(Date inputTime) {
        this.inputTime = inputTime;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 59 * hash + Objects.hashCode(this.counterPosition);
        hash = 59 * hash + Objects.hashCode(this.inputTime);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final CounterDataId other = (CounterDataId) obj;
        if (!Objects.equals(this.counterPosition, other.counterPosition)) {
            return false;
        }
        if (!Objects.equals(this.inputTime, other.inputTime)) {
            return false;
        }
        return true;
    }
    
}

src/main/java/net/ap57/tiger/ext/iot/linecounter/ui/bean/CounterPositionTable.java
/*
 * Copyright 2016 Arief Prihasanto <aphasan57 at gmail.com>.
 * All rights reserved

 * A lot of time, effort and money is spent designing and implementing the software.
 * All system design, text, graphics, the selection and arrangement thereof, and
 * all software compilations, underlying source code, software and all other material
 * on this software are copyright Arief Prihasanto <aphasan57 at gmail.com> and any affiliates.
 * 
 * In simple terms, every element of this software is protected by copyright.
 * Unless you have our express written permission, you are not allowed
 * to copy partially and or completely, modify partially and or completely,
 * use partially and or completely and or reproduce any part of this  software
 * in any way, shape and or form.
 * 
 * Taking material from other source code and or document Arief Prihasanto <aphasan57 at gmail.com> and affiliates has designed is
 * also prohibited. You can be prosecuted by the licensee as well as by us as licensor.
 * 
 * Any other use of materials of this software, including reproduction for purposes other
 * than that noted in the business agreement, modification, distribution, or republication,
 * without the prior written permission of Arief Prihasanto <aphasan57 at gmail.com> is strictly prohibited.
 * 
 * The source code, partially and or completely, shall not be presented and or shown
 * and or performed to public and or other parties without the prior written permission
 * of Arief Prihasanto <aphasan57 at gmail.com>

 */
package net.ap57.tiger.ext.iot.linecounter.ui.bean;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.enterprise.event.Event;
import javax.faces.context.FacesContext;
import javax.faces.event.ActionEvent;
import net.ap57.tiger.base.ui.pf.PFLazyDataTable;
import net.ap57.tiger.ext.iot.linecounter.dao.LineCounterDeviceFacade;
import net.ap57.tiger.ext.iot.linecounter.dao.CounterPositionFacade;
import net.ap57.tiger.ext.iot.linecounter.entity.LineCounterButton;
import net.ap57.tiger.ext.iot.linecounter.entity.LineCounterDevice;
import net.ap57.tiger.ext.iot.linecounter.entity.CounterPosition;
import net.ap57.tiger.std.hr.entity.WorkUnit;
import org.primefaces.context.RequestContext;
import org.primefaces.event.SelectEvent;

/**
 *
 * @author Arief Prihasanto <aphasan57 at gmail.com>
 */
public abstract class CounterPositionTable extends PFLazyDataTable<CounterPositionFacade, CounterPosition> {

    protected abstract LineCounterDeviceFacade getGroupOp();

    protected abstract Event<CounterPosition> getSelectionEventGenerator();

    protected abstract Event<WorkUnit> getClearSelectionEventGenerator();

    public WorkUnit getWorkUnit() {
        return (WorkUnit) getAttribute("workunit");
    }

    public void setWorkUnit(WorkUnit workunit) {
        setAttribute("workunit", workunit);
    }

    public boolean isLocking() {
        return (boolean) getAttribute("locking", false);
    }

    public void setLocking(boolean locked) {
        setAttribute("locking", locked);
    }

    public void notifyLocking(ActionEvent evt) {
        Map<String, String> params = FacesContext.getCurrentInstance().getExternalContext().getRequestParameterMap();
        boolean locked = Boolean.valueOf(params.get("locked"));
        System.out.println("LOCK = " + locked);
        setLocking(locked);
    }

    public int getColumns() {
        return (int) getAttribute("columns", 18);
    }

    public void setColumns(int columns) {
        setAttribute("columns", columns);
    }

    public List<CounterPosition> getPositions() {
        List<CounterPosition> positions = getOp().findAll(getLoadFilters());
        if (positions.isEmpty()) {
            return positions;
        } else {
            return positions.subList(1, 47);
        }
    }

    public List<CounterPosition> getQcPositions() {
        List<CounterPosition> positions = getOp().findAll(getLoadFilters());
        if (positions.isEmpty()) {
            return positions;
        } else {
            return positions.subList(0, 1);
        }
    }

    public void notifyBean(ActionEvent evt) {
        Map<String, String> params = FacesContext.getCurrentInstance().getExternalContext().getRequestParameterMap();
        String command = params.get("command");
        switch (command) {
            case "pair":
                onPair(params.get("sender"), params.get("button"));
                break;
            default:
                break;
        }

    }

    public void invalidateDisplay(ActionEvent evt) {
        System.out.println("INVALIDATE DISPLAY");
        Map<String, String> params = FacesContext.getCurrentInstance().getExternalContext().getRequestParameterMap();
        String[] arrStrPosNums = params.get("positionNumber").split(",");
        List<String> lstPosNums = new ArrayList<>();
        for (String strPosNum : arrStrPosNums) {
            int posNum = Integer.parseInt(strPosNum);
            if(posNum == 0) lstPosNums.add("qc-dt-tbl:" + posNum + ":counter");
            else lstPosNums.add("dt-tbl:" + (posNum - 1) + ":counter");
        }
        for(String update : lstPosNums) {
            System.out.println(update);
        }
        RequestContext rc = RequestContext.getCurrentInstance();
        rc.update(lstPosNums);
    }

    public void invalidateSelection(ActionEvent evt) {
        Map<String, String> params = FacesContext.getCurrentInstance().getExternalContext().getRequestParameterMap();
        String strPosNum = params.get("positionNumber");

        List<String> lstPosNums = new ArrayList<>();

        int posNum = Integer.parseInt(strPosNum);
        if (posNum == 0) {
            lstPosNums.add("qc-dt-tbl:" + (posNum) + ":counter-lnk");
        } else {
            lstPosNums.add("dt-tbl:" + (posNum - 1) + ":counter-lnk");
        }

        String strOldPosNum = "";
        Integer oldPos = getOldSelection();
        if (oldPos != null) {
            if (oldPos == 0) {                
                strOldPosNum = "" + oldPos;
                lstPosNums.add("qc-dt-tbl:" + strOldPosNum + ":counter-lnk");
            } else {
                strOldPosNum = "" + (oldPos - 1);
                lstPosNums.add("dt-tbl:" + strOldPosNum + ":counter-lnk");
            }
        }
        lstPosNums.add("detail-frm");
        lstPosNums.add("detail-frm:sampler-dt-tbl");

        RequestContext rc = RequestContext.getCurrentInstance();
        rc.update(lstPosNums);
    }

    public void notifyMessage(ActionEvent evt) {
//        Map<String, String> params = FacesContext.getCurrentInstance().getExternalContext().getRequestParameterMap();
//        ByteBuffer data = params.get("data");
//        Message msg = new Message(data);
//        System.out.println(msg.getSource());
    }

    protected void onPair(String sender, String button) {
        if (isQualifiedSender(sender)) {
            CounterPosition position = getSelection();
            if (position == null) {
                return;
            }

            LineCounterButton counter = counter = new LineCounterButton();
            LineCounterDevice cg = getGroupOp().find(sender);
            counter.setHostDevice(cg);
            cg.getButtons().put(counter.getInputNumber(), counter);
//            counter.setInputNumber(button);
//            counter.setLastCount(0);
//            counter.setMode(LineCounterButton.NORMAL_MODE);
//            getOp().repair(position, counter);
        }
    }

    @Override
    public boolean isCreateContextEmpty() {
        if (getWorkUnit() == null) {
            return true;
        }
        return super.isCreateContextEmpty();
    }

    @Override
    public void create(CounterPosition e) {
        e.setWorkUnit(getWorkUnit());
        super.create(e);
    }

    @Override
    protected Map<String, Object> getLoadFilters() {
        Map<String, Object> filters = new HashMap<>();
        filters.put("workUnit", getWorkUnit());
        return filters;
    }

    private boolean isQualifiedSender(String sender) {
        CounterPosition pos = getSelection();
        if (pos == null) {
            return false;
        }
        WorkUnit workUnit = pos.getWorkUnit();
        List<String> cids = null;
//        cids = getCoverageOp().getCounterGroupIdServices(workUnit);
        return cids.contains(sender);
    }

    public void onWorkUnitChange(SelectEvent evt) {
        setSelection(null);
        setWorkUnit((WorkUnit) evt.getObject());
        RequestContext rc = RequestContext.getCurrentInstance();
        String wuid = getWorkUnit().getId();
        rc.execute("onCounterUnitChange('" + wuid + "');"
                + "onManagerUnitChange('" + wuid + "')");
    }

    public void onEmployeeSelect(SelectEvent evt) {

    }

    public void resetAll(ActionEvent evt) {
        getOp().resetAll(getWorkUnit());
    }

    public void reset(ActionEvent evt) {
//        LineCounterButton counter = getSelection().getCounterButton();
//        if (counter != null) {
//            getOp().reset(counter);
//        }
    }

    public String onSelection(CounterPosition pos) {
        if (getSelection() == null) {
            return "";
        } else if (pos.equals(getSelection())) {
            return "-selected";
        } else {
            return "";
        }
    }

    public void generatePosition(ActionEvent evt) {
        getOp().generatePosition(getWorkUnit());
    }

    @Override
    public void setSelection(CounterPosition selection) {

        CounterPosition oldPos = getSelection();

        if (oldPos != null) {
            setOldSelection(oldPos.getPositionNumber());
        }

        if (isLocking() && selection != null) {
            getSelectionEventGenerator().fire(selection);
        } else if (isLocking() && selection == null) {
            WorkUnit unit = getWorkUnit();
            if (unit != null) {
                getClearSelectionEventGenerator().fire(unit);

src/main/java/net/ap57/tiger/ext/utility/entity/HelpDeskCase.java
/*
 * Copyright 2015 Arief Prihasanto <ariefp5758 at gmail.com>.
 * All rights reserved

 * A lot of time, effort and money is spent designing and implementing the software.
 * All system design, text, graphics, the selection and arrangement thereof, and
 * all software compilations, underlying source code, software and all other material
 * on this software are copyright Arief Prihasanto <ariefp5758 at gmail.com> and any affiliates.
 * 
 * In simple terms, every element of this software is protected by copyright.
 * Unless you have our express written permission, you are not allowed
 * to copy partially and or completely, modify partially and or completely,
 * use partially and or completely and or reproduce any part of this  software
 * in any way, shape and or form.
 * 
 * Taking material from other source code and or document Arief Prihasanto <ariefp5758 at gmail.com> and affiliates has designed is
 * also prohibited. You can be prosecuted by the licensee as well as by us as licensor.
 * 
 * Any other use of materials of this software, including reproduction for purposes other
 * than that noted in the business agreement, modification, distribution, or republication,
 * without the prior written permission of Arief Prihasanto <ariefp5758 at gmail.com> is strictly prohibited.
 * 
 * The source code, partially and or completely, shall not be presented and or shown
 * and or performed to public and or other parties without the prior written permission
 * of Arief Prihasanto <ariefp5758 at gmail.com>

 */
package net.ap57.tiger.ext.utility.entity;

import java.io.Serializable;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Lob;
import javax.persistence.ManyToOne;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import net.ap57.tiger.base.entity.PartyRole;
import net.ap57.tiger.base.entity.StringKeyedEntity;
import net.ap57.tiger.std.hr.entity.WorkUnit;
import net.ap57.tiger.std.system.entity.SecurityUser;

/**
 *
 * @author Arief Prihasanto <ariefp5758 at gmail.com>
 */
@Entity
@IdClass(HelpDeskCaseId.class)
public class HelpDeskCase extends StringKeyedEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    @Id
    @ManyToOne
    private PartyRole srcWorkUnit;

    @Id
    @Temporal(TemporalType.TIMESTAMP)
    private Date submitDate;

    @Temporal(TemporalType.TIMESTAMP)
    private Date solvedDate;

    @ManyToOne
    private PartyRole destWorkUnit;

    @Lob
    private String content;

    private boolean solved;

    @ManyToOne
    private SecurityUser creator;

    public WorkUnit getSrcWorkUnit() {
        return (WorkUnit) srcWorkUnit;
    }

    public void setSrcWorkUnit(WorkUnit srcWorkUnit) {
        this.srcWorkUnit = srcWorkUnit;
    }

    public Date getSubmitDate() {
        return submitDate;
    }

    public void setSubmitDate(Date submitDate) {
        this.submitDate = submitDate;
    }

    public Date getSolvedDate() {
        return solvedDate;
    }

    public void setSolvedDate(Date solvedDate) {
        this.solvedDate = solvedDate;
    }

    public WorkUnit getDestWorkUnit() {
        return (WorkUnit) destWorkUnit;
    }

    public void setDestWorkUnit(WorkUnit destWorkUnit) {
        this.destWorkUnit = destWorkUnit;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public boolean isSolved() {
        return solved;
    }

    public void setSolved(boolean solved) {
        this.solved = solved;
    }

    public SecurityUser getCreator() {
        return creator;
    }

    public void setCreator(SecurityUser creator) {
        this.creator = creator;
    }

    @Override
    public void prePersist() {
        super.prePersist();
        submitDate = Calendar.getInstance().getTime();
    }

    public String getStrSubmitDate() {
        DateFormat sdf = new SimpleDateFormat("MMMMM d, yyyy HH:mm:ss");
        if (submitDate != null) {
            return sdf.format(submitDate);
        } else {
            return null;
        }
    }
}

src/main/webapp/utility/general/helpdesk.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="/WEB-INF/templates/page.xhtml"
                xmlns:p="http://primefaces.org/ui"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:pe="http://primefaces.org/ui/extensions" >

    <ui:define name="initializer">
        <f:loadBundle basename="net.ap57.tiger.ext.utility.strings" var="msgs" />
        #{helpDeskPage.initLayout}
    </ui:define>

    <ui:define name="editor-tool">
        <p:commandButton title="Create" icon="ui-icon-plusthick" immediate="true"  
                         disabled="#{helpDeskPage.get('helpDeskCaseTable').createContextEmpty}"
                         actionListener="#{helpDeskPage.get('helpDeskCaseTable').prepareTransient}"
                         oncomplete="PF('createDlg').show()" update=":create-dlg :messages" />
        <p:commandButton title="Edit" icon="ui-icon-pencil" immediate="true" 
                         disabled="#{helpDeskPage.get('helpDeskCaseTable').updateContextEmpty}"
                         update=":edit-dlg :messages" oncomplete="PF('editDlg').show()" />
        <p:commandButton title="Delete" icon="ui-icon-trash" immediate="true"
                         disabled="#{helpDeskPage.get('helpDeskCaseTable').deleteContextEmpty}"
                         update=":delete-dlg" oncomplete="PF('deleteDlg').show()" /> 
        <p:commandButton title="All Data" icon="ui-icon-script" immediate="true"
                         update=":alldata-dlg" oncomplete="PF('alldataDlg').show()" />        
    </ui:define>

    <ui:define name="editor-content">
        <h:outputStylesheet library="ext" name="utility/css/jquery.countup.css" />
        <h:outputScript library="ext" name="utility/js/jquery.countup.js" />
        <h:outputScript>
            function countingUp(idx, startFrom) {$('.countup').eq(idx).countup(startFrom)}
        </h:outputScript>

        <h:form id="dt-frm">

            <p:dataTable id="dt-tbl" value="#{helpDeskPage.get('helpDeskCaseTable').model}" var="item" rowIndexVar="rowIndexVar0"
                         selectionMode="multiple" selection="#{helpDeskPage.get('helpDeskCaseTable').selections}"
                         emptyMessage="Empty Data" paginator="true" paginatorAlwaysVisible="false"
                         lazy="true" rowsPerPageTemplate="5 10 15 20 25" rows="15"
                         paginatorTemplate="{CurrentPageReport} {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}">

                <p:ajax event="contextMenu" process="dt-tbl" update=":messages" />
                <p:ajax event="rowSelect" process="dt-tbl" update=":messages" />
                <p:ajax event="rowUnselect" process="dt-tbl" update=":messages" />

                <p:columnGroup type="header">
                    <p:row>
                        <p:column headerText="From" width="100" />
                        <p:column headerText="Problem" />
                        <p:column headerText="To"  width="100"/>
                        <p:column headerText="Logger" width="200" />
                        <p:column headerText="Time-lapse" width="150" />
                    </p:row>
                </p:columnGroup>

                <p:column style="text-align: center">
                    <h:outputText value="#{item.srcWorkUnit}" />
                </p:column>

                <p:column>
                    <h:outputText value="#{item.content}" />
                </p:column>

                <p:column style="text-align: center">
                    <h:outputText value="#{item.destWorkUnit}" />
                </p:column>

                <p:column style="text-align: center">
                    <h:outputText value="#{item.creator.person.name}" />
                </p:column>

                <p:column style="text-align: center">
                    <div class="countup"  style="text-align: center"><h:outputScript >countingUp(#{rowIndexVar0}, '#{item.strSubmitDate}')</h:outputScript></div>
                </p:column>

            </p:dataTable>           


            <p:contextMenu for="dt-tbl">
                <p:menuitem value="Create" icon="ui-icon-plusthick" immediate="true"
                            actionListener="#{helpDeskPage.get('helpDeskCaseTable').prepareTransient}"
                            oncomplete="PF('createDlg').show()" update=":create-dlg :messages" />
                <p:menuitem value="Edit" icon="ui-icon-pencil" immediate="true"
                            update=":edit-dlg :messages" oncomplete="PF('editDlg').show()" />
                <p:menuitem value="Delete" icon="ui-icon-trash" immediate="true"
                            update=":delete-dlg" oncomplete="PF('deleteDlg').show()" />
                <p:menuitem value="Solved" icon="ui-icon-check" immediate="true"
                            actionListener="#{helpDeskPage.get('helpDeskCaseTable').solved}"
                            update=":dt-frm:dt-tbl :messages" />
            </p:contextMenu>

        </h:form>
    </ui:define>

    <ui:define name="statusbar">

    </ui:define>

    <ui:define name="components">

        <p:dialog dynamic="true" id="alldata-dlg" widgetVar="alldataDlg" modal="true" resizable="false" header="Helpdesk Archive " width="50%" >
            <h:form id="alldata-frm">

                <p:dataTable id="dt-tbl" value="#{helpDeskPage.get('alldataTable').model}" var="item" rowIndexVar="rowIndexVar0"
                             selectionMode="multiple" selection="#{helpDeskPage.get('helpDeskCaseTable').selections}"
                             emptyMessage="Empty Data" paginator="true" paginatorAlwaysVisible="false"
                             lazy="true" rowsPerPageTemplate="5 10 15 20 25" rows="15"
                             paginatorTemplate="{CurrentPageReport} {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}">

                    <p:columnGroup type="header">
                        <p:row>
                            <p:column headerText="From" width="100" />
                            <p:column headerText="Problem" />
                            <p:column headerText="To"  width="100"/>
                            <p:column headerText="Submit" />
                            <p:column headerText="Solved" />
                        </p:row>
                    </p:columnGroup>

                    <p:column style="text-align: center">
                        <h:outputText value="#{item.srcWorkUnit}" />
                    </p:column>

                    <p:column>
                        <h:outputText value="#{item.content}" />
                    </p:column>

                    <p:column style="text-align: center">
                        <h:outputText value="#{item.destWorkUnit}" />
                    </p:column>

                    <p:column style="text-align: center">
                        <h:outputText value="#{item.submitDate}" >
                            <f:convertDateTime pattern="dd/MM/YYYY HH:mm" />
                        </h:outputText>
                    </p:column>

                    <p:column style="text-align: center">
                        <h:outputText value="#{item.solvedDate}" >
                            <f:convertDateTime pattern="dd/MM/YYYY HH:mm" />
                        </h:outputText>
                    </p:column>

                </p:dataTable> 
            </h:form>
        </p:dialog>

        <p:dialog dynamic="true" id="create-dlg" widgetVar="createDlg" modal="true" resizable="false" header="Create Dialog" >
            <h:form id="create-frm">
                <p:panelGrid columns="2">

                    <p:outputLabel for="src" value="From" />
                    <p:selectOneMenu id="src" value="#{helpDeskPage.get('helpDeskCaseTable').selection.srcWorkUnit}" 
                                     converter="#{helpDeskPage.get('workUnitList')}" >
                        <f:selectItem itemLabel="Select Work Unit" itemValue="" />
                        <f:selectItems value="#{helpDeskPage.get('workUnitList').data}" var="unit" 
                                       itemValue="#{unit}" itemLabel="#{unit.name}" />
                    </p:selectOneMenu>

                    <p:outputLabel for="dest" value="To" />
                    <p:selectOneMenu id="dest" value="#{helpDeskPage.get('helpDeskCaseTable').selection.destWorkUnit}" 
                                     converter="#{helpDeskPage.get('workUnitList')}" >
                        <f:selectItem itemLabel="Select Work Unit" itemValue="" />
                        <f:selectItems value="#{helpDeskPage.get('workUnitList').data}" var="unit" 
                                       itemValue="#{unit}" itemLabel="#{unit.name}" />
                    </p:selectOneMenu>              

                    <p:outputLabel for="content" value="Content" />
                    <p:inputTextarea value="#{helpDeskPage.get('helpDeskCaseTable').selection.content}" id="content" label="Content" />

                    <f:facet name="footer">
                        <p:commandButton value="Create" actionListener="#{helpDeskPage.get('helpDeskCaseTable').create}"
                                         update=":dt-frm:dt-tbl :messages" oncomplete="PF('createDlg').hide()" icon="ui-icon-check" />
                    </f:facet>

                </p:panelGrid>
            </h:form>
        </p:dialog>

        <p:dialog dynamic="true" id="edit-dlg" widgetVar="editDlg" modal="true" resizable="false" header="Edit Dialog" >
            <h:form id="edit-frm">
                <p:panelGrid columns="2">

                    <p:outputLabel for="dest" value="To" />
                    <p:selectOneMenu id="dest" value="#{helpDeskPage.get('helpDeskCaseTable').selection.destWorkUnit}" 
                                     converter="#{helpDeskPage.get('workUnitList')}" >
                        <f:selectItem itemLabel="Select Work Unit" itemValue="" />
                        <f:selectItems value="#{helpDeskPage.get('workUnitList').data}" var="unit" 
                                       itemValue="#{unit}" itemLabel="#{unit.name}" />
                    </p:selectOneMenu>                

                    <p:outputLabel for="content" value="Content" />
                    <p:inputTextarea value="#{helpDeskPage.get('helpDeskCaseTable').selection.content}" id="content" label="Content" />

                    <f:facet name="footer">
                        <p:commandButton value="Update" actionListener="#{helpDeskPage.get('helpDeskCaseTable').update}"
                                         update=":dt-frm:dt-tbl :messages" oncomplete="PF('editDlg').hide()" icon="ui-icon-refresh" />
                    </f:facet>

                </p:panelGrid>
            </h:form>
        </p:dialog>

        <p:confirmDialog id="delete-dlg" widgetVar="deleteDlg" closable="false" header="Confirmation"
                         message="Are you sure about deleting it ?">
            <h:form>
                <p:commandButton value="Yes Sure" icon="ui-icon-check" immediate="true"
                                 actionListener="#{helpDeskPage.get('helpDeskCaseTable').delete}"
                                 oncomplete="PF('deleteDlg').hide()" update=":dt-frm:dt-tbl :messages" />
                <p:commandButton value="Not Yet" icon="ui-icon-closethick" type="button" onclick="PF('deleteDlg').hide()"/>
            </h:form>
        </p:confirmDialog>
    </ui:define>

</ui:composition>